---
booktitle: Proceedings of Machine Learning for Health
shortname: ML4H
volume: '158'
year: '2021'
start: 2021-12-04
end: 2021-12-04
published: 2021-11-28
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: ML4H-2021
month: 0
cycles: false
bibtex_editor: Roy, Subhrajit and Pfohl, Stephen and Rocheteau, Emma and Tadesse,
  Girmaw Abebe and Oala, Luis and Falck, Fabian and Zhou, Yuyin and Shen, Liyue and
  Zamzmi, Ghada and Mugambi, Purity and Zirikly, Ayah and McDermott, Matthew B. A.
  and Alsentzer, Emily
editor:
- given: Subhrajit
  family: Roy
- given: Stephen
  family: Pfohl
- given: Emma
  family: Rocheteau
- given: Girmaw Abebe
  family: Tadesse
- given: Luis
  family: Oala
- given: Fabian
  family: Falck
- given: Yuyin
  family: Zhou
- given: Liyue
  family: Shen
- given: Ghada
  family: Zamzmi
- given: Purity
  family: Mugambi
- given: Ayah
  family: Zirikly
- given: Matthew B. A.
  family: McDermott
- given: Emily
  family: Alsentzer
title: Proceedings of Machine Learning Research
description: |
  Proceedings of Machine Learning for Health
    Held in Virtual Conference, Anywhere, Earth on 04 December 2021

  Published as Volume 158 by the Proceedings of Machine Learning Research on 28 November 2021.

  Volume Edited by:
    Subhrajit Roy
    Stephen Pfohl
    Emma Rocheteau
    Girmaw Abebe Tadesse
    Luis Oala
    Fabian Falck
    Yuyin Zhou
    Liyue Shen
    Ghada Zamzmi
    Purity Mugambi
    Ayah Zirikly
    Matthew B. A. McDermott
    Emily Alsentzer

  Series Editors:
    Neil D. Lawrence
    * Mark Reid
date_str: 04 Dec
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v158"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v158
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v158
email: ''
conference:
  name: Machine Learning for Health
  url: https://ml4health.github.io/2021/
  location: Virtual Conference, Anywhere, Earth
  dates:
  - 2021-12-04
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v158/ml4h21.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v158/ml4h21.bib
